FROM python:3.12-slim

WORKDIR /app

COPY scripts/requirements.backend.txt ./requirements.backend.txt
RUN pip install -r requirements.backend.txt --no-cache-dir
RUN pip install ddgs

COPY . .
COPY .env.docker ./.env

EXPOSE 8000

ENV HOST=0.0.0.0 \
	PORT=8000 

CMD ["python", "-m", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
